### ISSUE TITLE
CLI mode

### ISSUE THREAD

**Issue by hrvstr** [mariusberget92/scenex#1]
Can this library be used as CLI tool that outputs JSON like https://github.com/matiassingers/scene-release?

**Comment by mariusberget92** [comment]
Hi! I have not implemented CLI feature, no. Shouldn't be too hard to implement though. I'll see what I can do.

**Comment by mariusberget92** [comment]
Added a very simple CLI. Just run `node cli.js <release-name>` from the scenex package directory, without the gator signs ofc. Or you could simplify it by adding a PATH environment variable on Windows.

**Comment by hrvstr** [comment]
Awesome, thank you very much. Works much better than my scene-release fork 😂

**Comment by mariusberget92** [comment]
No worries. :)
